#!/usr/bin/env lua

-- Add sbarlua to path
package.cpath = package.cpath .. ";" .. (
  os.getenv("SKETCHYBAR_LUA_PATH")                                      -- Get from env var instead, nix-friendly
  or ("/Users/" .. os.getenv("USER") .. "/.local/share/sketchybar_lua") -- Official install path 
) .. "/?.so"

sbar = require("sketchybar")

-- Bundle the entire initial configuration into a single message to sketchybar
-- This improves startup times drastically, try removing both the begin and end
-- config calls to see the difference -- yeah..
sbar.begin_config()
sbar.hotload(true)
require("init")
sbar.end_config()

log("lua-main","Finished loading")

-- Run the event loop of the sketchybar module (without this there will be no
-- callback functions executed in the lua module)
sbar.event_loop()