require("items.widgets.battery")
require("items.widgets.volume")
require("items.widgets.wifi")
require("items.widgets.brew")
require("items.widgets.pomodoro")
require("items.widgets.cpu")
require("items.widgets.ram")
require("items.widgets.ssd")
