#!/bin/bash

options=(
  style=round
  width=4
  hidpi=off
  # active_color=0xff89dceb # Catppuccin Mocha - Glow
  # active_color=0xffeba0ac # Catppuccin Mocha - Maroon
  active_color="gradient(top_right=0xff89dceb,bottom_left=0xffeba0ac)"
  blur_radius=64
)

borders "${options[@]}"
