#!/bin/bash

options=(
  style=round
  width=5
  hidpi=on
  # active_color=0xffe1e3e4
  # active_color="gradient(top_left=0xffe1e3e4,bottom_right=0xff222222)"
  active_color="gradient(top_left=0xffebbcba,bottom_right=0xffc4a7e7)"
  active_color="gradient(top_right=0xff31748f,bottom_left=0xffeb6f92)" # RosePine Dark colorwave from Omarchy theme: rose, pine, love, iris
  inactive_color=0xff494d64
  background_color=0x302c2e34
  # blur_radius=64
)

borders "${options[@]}"
# active_color="gradient(top_left=0xffebbcba,bottom_right=0xffeb6f92)"
# active_color="gradient(top_right=0xff31748f,bottom_left=0xffc4a7e7)" # RosePine Dark colorwave from Omarchy theme: rose, pine, love, iris
