return {
	["default"] = ":default:",

	-- AI
	["Claude"] = ":claude:",
	["ChatGPT"] = ":openai:",
	["OpenAI Translator"] = ":openai_translator:",
	["Copilot"] = ":copilot:",

	-- Browser
	["Arc"] = ":arc:",
	["Chromium"] = ":google_chrome:",
	["Google Chrome"] = ":google_chrome:",
	["Google Chrome Canary"] = ":google_chrome:",
	["Firefox"] = ":firefox:",
	["Firefox Developer Edition"] = ":firefox_developer_edition:",
	["Firefox Nightly"] = ":firefox_developer_edition:",
	["LibreWolf"] = ":libre_wolf:",
	["Microsoft Edge"] = ":microsoft_edge:",
	["Microsoft Edge Dev"] = ":microsoft_edge:",
	["Min"] = ":min_browser:",
	["Opera"] = ":opera:",
	["Orion"] = ":orion:",
	["Orion RC"] = ":orion:",
	["Brave Browser"] = ":brave_browser:",
	["Tor Browser"] = ":tor_browser:",
	["Safari"] = ":safari:",
	["Safari浏览器"] = ":safari:",
	["Safari Technology Preview"] = ":safari:",
	["Vivaldi"] = ":vivaldi:",
	["Yandex Browser"] = ":yandex_bower:",
	["Yandex Browser"] = ":yandex_bower:",
	["Yandex"] = ":yandex_bower:",
	["Zen"] = ":zen_browser:",
	["Twilight"] = ":zen_browser:",
	["qutebrowser"] = ":qute_browser:",

	-- Calendar
	["Cron"] = ":calendar:",
	["Amie"] = ":calendar:",
	["Calendrier"] = ":calendar:",
	["カレンダー"] = ":calendar:",
	["Notion Calendar"] = ":calendar:",
	["Calendar"] = ":calendar:",
	["日历"] = ":calendar:",
	["Fantastical"] = ":calendar:",
	["BusyCal"] = ":busycal:",

	-- Design
	["Affinity Designer"] = ":affinity_designer:",
	["Affinity Designer 2"] = ":affinity_designer_2:",
	["Affinity Photo"] = ":affinity_photo:",
	["Affinity Photo 2"] = ":affinity_photo_2:",
	["Affinity Publisher"] = ":affinity_publisher:",
	["Affinity Publisher 2"] = ":affinity_publisher_2:",
	["Adobe Lightroom"] = ":lightroom:",
	["Adobe Illustrator"] = ":illustrator:",
	["Illustrator"] = ":illustrator:",
	["Adobe InDesign"] = ":indesign:",
	["InDesign"] = ":indesign:",
	["Lightroom Classic"] = ":lightroomclassic:",
	["DaVinci Resolve"] = ":davinciresolve:",
	["SF Symbols"] = ":sf_symbols:",
	["Adobe Bridge"] = ":adobe_bridge:",
	["Adobe Photoshop"] = ":photoshop:",
	["draw.io"] = ":draw_io:",
	["Inkscape"] = ":inkscape:",
	["Freeform"] = ":freeform:",
	["Fusion"] = ":fusion:",
	["Miro"] = ":miro:",
	["Zeplin"] = ":zeplin:",
	["Phoenix Slides"] = ":phoenix_slides:",
	["OrcaSlicer"] = ":orcaslicer:",
	["PrusaSlicer"] = ":prusaslicer:",
	["SuperSlicer"] = ":prusaslicer:",
	["Bambu Studio"] = ":bambu_studio:",

	-- Developer
	["Docker"] = ":docker:",
	["Docker Desktop"] = ":docker:",
	["OrbStack"] = ":orbstack:",
	["GitHub Desktop"] = ":git_hub:",
	["Android Studio"] = ":android_studio:",
	["WebStorm"] = ":web_storm:",
	["Arduino"] = ":arduino:",
	["Arduino IDE"] = ":arduino:",
	["Cypress"] = ":cypress:",
	["DataGrip"] = ":datagrip:",
	["DataSpell"] = ":dataspell:",
	["DBeaver"] = ":dbeaver:",
	["GoLand"] = ":goland:",
	["Fork"] = ":fork:",
	["Insomnia"] = ":insomnia:",
	["PhpStorm"] = ":php_storm:",
	["Postman"] = ":postman:",
	["Rider"] = ":rider:",
	["JetBrains Rider"] = ":rider:",
	["Replit"] = ":replit:",
	["Repo Prompt"] = ":repo_prompt:",
	["MongoDB Compass"] = ":mongodb:",
	["Sequel Ace"] = ":sequel_ace:",
	["Sequel Pro"] = ":sequel_pro:",
	["Studio 3T"] = ":studio_3t:",
	["TablePlus"] = ":tableplus:",
	["Tiny RDM"] = ":tinyrdm:",
	["Tower"] = ":tower:",
	["MAMP"] = ":mamp:",
	["MAMP PRO"] = ":mamp:",
	["Godot"] = ":godot:",

	-- Editor
	["Atom"] = ":atom:",
	["Code"] = ":code:",
	["Code - Insiders"] = ":code:",
	["Cursor"] = ":cursor:",
	["VSCodium"] = ":vscodium:",
	["PyCharm"] = ":pycharm:",
	["IntelliJ IDEA"] = ":idea:",
	["Neovide"] = ":neovide:",
	["neovide"] = ":neovide:",
	["nvim"] = ":neovim:",
	["MacVim"] = ":vim:",
	["Vim"] = ":vim:",
	["VimR"] = ":vim:",
	["Emacs"] = ":emacs:",
	["Sublime Text"] = ":sublime_text:",
	["CotEditor"] = ":coteditor:",
	["Nova"] = ":nova:",
	["Zed"] = ":zed:",
	["Kakoune"] = ":kakoune:",

	-- Entertainment
	["Steam Helper"] = ":steam:",
	["Steam"] = ":steam:",
	["FreeTube"] = ":freetube:",
	["Battle.net"] = ":battle_net:",
	["League of Legends"] = ":league_of_legends:",
	["Bilibili"] = ":bilibili:",
	["哔哩哔哩"] = ":bilibili:",

	-- Mail
	["Canary Mail"] = ":mail:",
	["HEY"] = ":mail:",
	["Mail"] = ":mail:",
	["Mailspring"] = ":mail:",
	["MailMate"] = ":mail:",
	["Mimestream"] = ":mail:",
	["Superhuman"] = ":mail:",
	["Notion Mail"] = ":mail:",
	["Spark"] = ":mail:",
	["Spark Desktop"] = ":spark:",
	["邮件"] = ":mail:",
	["メール"] = ":mail:",
	["Airmail"] = ":airmail:",
	["Thunderbird"] = ":thunderbird:",

	-- Media
	["Spotify"] = ":spotify:",
	["Music"] = ":music:",
	["NetEaseMusic"] = ":music:",
	["LX Music"] = ":music:",
	["网易云音乐"] = ":netease_music:",
	["tauonmb"] = ":netease_music:",
	["IINA"] = ":iina:",
	["Audacity"] = ":audacity:",
	["Deezer"] = ":deezer:",
	["TIDAL"] = ":tidal:",
	["Yandex Music"] = ":yandex_music:",
	["音乐"] = ":music:",
	["Musique"] = ":music:",
	["ミュージック"] = ":music:",
	["Podcasts"] = ":podcasts:",
	["播客"] = ":podcasts:",
	["QQ音乐"] = ":qqmusic:",
	["QQMusic"] = ":qqmusic:",
	["Infuse"] = ":infuse:",
	["Jellyfin Media Player"] = ":jellyfin:",
	["Plex"] = ":plex:",
	["Plexamp"] = ":plexamp:",
	["Moonlight"] = ":moonlight:",
	["Kodi"] = ":kodi:",

	-- Microsoft Office Sweet
	["Microsoft Excel"] = ":microsoft_excel:",
	["Microsoft Outlook"] = ":microsoft_outlook:",
	["Microsoft PowerPoint"] = ":microsoft_power_point:",
	["Microsoft Teams"] = ":microsoft_teams:",
	["Microsoft Teams (work or school)"] = ":microsoft_teams:",
	["Microsoft Word"] = ":microsoft_word:",

	-- MacOS Default Apps
	["Activity Monitor"] = ":cpu:",
	["Finder"] = ":finder:",
	["访达"] = ":finder:",
	["Spotlight"] = ":spotlight:",
	["Keynote"] = ":keynote:",
	["iPhone Mirroring"] = ":iphone_mirroring:",
	["Xcode"] = ":xcode:",
	["App Store"] = ":app_store:",
	["System Preferences"] = ":gear:",
	["System Settings"] = ":gear:",
	["Font Book"] = ":book:",
	["Notes"] = ":notes:",
	["备忘录"] = ":notes:",
	["メモ"] = ":notes:",
	["FaceTime"] = ":face_time:",
	["FaceTime 通话"] = ":face_time:",
	["Calculator"] = ":calculator:",
	["Calculette"] = ":calculator:",
	["Color Picker"] = ":color_picker:",
	["数码测色计"] = ":color_picker:",
	["Weather"] = ":weather:",
	["Maps"] = ":maps:",
	["Google Maps"] = ":maps:",
	["マップ"] = ":maps:",
	["Passwords"] = ":passwords:",
	["Photos"] = ":photos:",
	["Reminders"] = ":reminders:",
	["提醒事项"] = ":reminders:",
	["Rappels"] = ":reminders:",
	["リマインダー"] = ":reminders:",
	["Messages"] = ":messages:",
	["信息"] = ":messages:",
	["Nachrichten"] = ":messages:",
	["メッセージ"] = ":messages:",
	["系统设置"] = ":gear:",
	["Réglages Système"] = ":gear:",
	["システム設定"] = ":gear:",
	["TextEdit"] = ":textedit:",

	-- Multimedia
	["VLC"] = ":vlc:",
	["Final Cut Pro"] = ":final_cut_pro:",
	["OBS"] = ":obsstudio:",
	["Blender"] = ":blender:",
	["Figma"] = ":figma:",
	["Sketch"] = ":sketch:",
	["mpv"] = ":mpv:",
	["Live"] = ":ableton:",
	["Logic Pro"] = ":logicpro:",

	-- Network
	-- TODO 目前没有:clash:，先用着kiro的icon
	["FlClash"] = ":kiro:",
	["Clash Verge"] = ":kiro:",
	["Mullvad Browser"] = ":mullvad_browser:",
	["NordVPN"] = ":nord_vpn:",
	["OpenVPN Connect"] = ":openvpn_connect:",
	["Surfshark"] = ":surfshark:",
	["Quantumult X"] = ":quantumult_x:",

	-- Note Takers
	["Antinote"] = ":notes:",
	["Anki"] = ":anki:",
	["Bear"] = ":bear:",
	["Obsidian"] = ":obsidian:",
	["Typora"] = ":text:",
	["Anytype"] = ":anytype:",
	["Drafts"] = ":drafts:",
	["Evernote Legacy"] = ":evernote_legacy:",
	["Joplin"] = ":joplin:",
	["Logseq"] = ":logseq:",
	["Tana"] = ":tana:",
	["Inkdrop"] = ":inkdrop:",
	["DEVONthink 3"] = ":devonthink3:",
	["Notability"] = ":notability:",

	-- Office 办公
	["Matlab"] = ":matlab:",
	["Numbers"] = ":numbers:",
	["Numbers 表格"] = ":numbers:",
	["Pages"] = ":pages:",
	["Pages 文稿"] = ":pages:",
	["Keynote 讲演"] = ":keynote:",
	["Grammarly Editor"] = ":grammarly:",
	["LanguageTool for Desktop"] = ":languagetool_for_desktop:",

	-- PDF
	["UPDF"] = ":pdf:",
	["Preview"] = ":pdf:",
	["Skim"] = ":pdf:",
	["zathura"] = ":pdf:",
	["sioyek"] = ":pdf:",
	["预览"] = ":pdf:",
	["Aperçu"] = ":pdf:",
	["プレビュー"] = ":pdf:",
	["PDF Expert"] = ":pdf_expert:",

	-- Productivity
	["Things"] = ":things:",
	["Microsoft To Do"] = ":things:",
	["Todoist"] = ":todoist:",
	["TickTick"] = ":tick_tick:",
	["ClickUp"] = ":click_up:",
	["Linear"] = ":linear:",
	["Trello"] = ":trello:",
	["OmniFocus"] = ":omni_focus:",
	["PomoDone App"] = ":pomodone:",
	["superProductivity"] = ":superproductivity:",
	["Toggl Track"] = ":toggl_track:",

	-- Proton
	["Proton Mail"] = ":proton_mail:",
	["Proton Mail Bridge"] = ":proton_mail:",
	["Proton VPN"] = ":proton_vpn:",
	["ProtonVPN"] = ":proton_vpn:",

	-- Remote Access
	["RustDesk"] = ":rustdesk:",
	["Microsoft Remote Desktop"] = ":microsoft_remote_desktop:",
	["Royal TSX"] = ":royaltsx:",

	-- Social
	["Discord"] = ":discord:",
	["Telegram"] = ":telegram:",
	["QQ"] = ":qq:",
	["微信"] = ":wechat:",
	["WeChat"] = ":wechat:",
	["小红书"] = ":book:",
	["DingTalk"] = ":dingtalk:",
	["钉钉"] = ":dingtalk:",
	["阿里钉"] = ":dingtalk:",
	["Discord Canary"] = ":discord:",
	["Discord PTB"] = ":discord:",
	["Vesktop"] = ":discord:",
	["Equibop"] = ":discord:",
	["Tweetbot"] = ":twitter:",
	["Twitter"] = ":twitter:",
	["WhatsApp"] = ":whats_app:",
	["‎WhatsApp"] = ":whats_app:",
	["Messenger"] = ":messenger:",
	["Caprine"] = ":caprine:",
	["Amazon Chime"] = ":chime:",
	["카카오톡"] = ":kakaotalk:",
	["KakaoTalk"] = ":kakaotalk:",
	["LINE"] = ":line:",
	["企业微信"] = ":wecom:",
	["WeCom"] = ":wecom:",
	["Signal"] = ":signal:",
	["Mattermost"] = ":mattermost:",
	["Skype"] = ":skype:",
	["Slack"] = ":slack:",
	["Element"] = ":element:",
	["Session"] = ":session:",
	["Zulip"] = ":zulip:",
	["TeamSpeak 3"] = ":team_speak:",
	["zoom.us"] = ":zoom:",

	-- Terminal
	["Alacritty"] = ":alacritty:",
	["Hyper"] = ":terminal:",
	["Ghostty"] = ":ghostty:",
	["iTerm2"] = ":terminal:",
	["kitty"] = ":kitty:",
	["Terminal"] = ":terminal:",
	["终端"] = ":terminal:",
	["ターミナル"] = ":terminal:",
	["WezTerm"] = ":terminal:",
	["Warp"] = ":warp:",
	["Tabby"] = ":tabby:",
	["Rio"] = ":rio:",

	-- Utilities
	["BetterTouchTool"] = ":bettertouchtool:",
	["Keyboard Maestro"] = ":keyboard_maestro:",
	["Cold Turkey Blocker"] = ":cold_turkey_blocker:",
	["CleanMyMac X"] = ":desktop:",
	["App Eraser"] = ":app_eraser:",
	["Pearcleaner"] = ":pearcleaner:",
	["Numi"] = ":notes:",

	-- Virtual Box
	["Parallels Desktop"] = ":parallels:",
	["Parsec"] = ":parsec:",
	["UTM"] = ":utm:",
	["VMware Fusion"] = ":vmware_fusion:",
	["Citrix Workspace"] = ":citrix:",
	["Citrix Viewer"] = ":citrix:",

	-- Other
	["Raycast"] = ":raycast:",
	["Bitwarden"] = ":bit_warden:",
	["Dropbox"] = ":dropbox:",
	["Notion"] = ":notion:",
	["1Password"] = ":one_password:",
	["Alfred"] = ":alfred:",
	["MoneyMoney"] = ":bank:",
	["GrandTotal"] = ":dollar:",
	["Receipts"] = ":dollar:",
	["Marta"] = ":marta:",
	["Double Commander"] = ":doublecmd:",
	["Transmit"] = ":transmit:",
	["Folx"] = ":folx:",
	["Calibre"] = ":book:",
	["calibre"] = ":calibre:",
	["Reeder"] = ":reeder5:",
	["BluOS Controller"] = ":bluos_controller:",
	["Setapp"] = ":setapp:",
	["Creative Cloud"] = ":creative_cloud:",
	["Raindrop.io"] = ":raindrop_io:",
	["Noodl"] = ":noodl:",
	["Noodl Editor"] = ":noodl:",
	["LM Studio"] = ":lm_studio:",
	["LocalSend"] = ":localsend:",
	["Pine"] = ":pine:",
	["Iris"] = ":iris:",
	["Zotero"] = ":zotero:",
	["Yuque"] = ":yuque:",
	["语雀"] = ":yuque:",
	["Home Assistant"] = ":home_assistant:",
	["Pi-hole Remote"] = ":pihole:",
	["KeePassXC"] = ":kee_pass_x_c:",
	["Android Messages"] = ":android_messages:",
	["Open Video Downloader"] = ":open_video_downloader:",
	["Default"] = ":default:",
}
